name: build-sb-zfs-kernel
on:
  pull_request:
  merge_group:
  schedule:
    - cron: '17 23 * * *'
  workflow_dispatch:
env:
    IMAGE_NAME: sb-zfs-kernel
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push ucore-kmods image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        coreos_version: [stable, testing]
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ steps.registry_case.outputs.lowercase }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=A caching layer for pre-built kmod RPMs
            org.opencontainers.image.version=${{ steps.labels.outputs.VERSION }}
            ostree.linux=${{ steps.labels.outputs.LINUX }}
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
            #tags: |
            #  ${{ env.METADATA_TAGS }}
          tags: |
            latest


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build/push image using docker buildx action
      - name: Build and Push Image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./Containerfile
          #build-args: |
          #  SOURCE_IMAGE=${{ env.SOURCE_IMAGE }}
          #  COREOS_VERSION=${{ matrix.coreos_version }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
